services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backup:
    image: postgres:15.3-alpine
    volumes:
      - ./backup.sh:/backup.sh
      - ./crontab:/etc/crontabs/root
      - ./backups:/backups
    entrypoint: /bin/sh -c "
      apk add --no-cache aws-cli && chmod 0644 /etc/crontabs/root && chmod +x /backup.sh && crond -f -l 8"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: db  # Connect to the PostgreSQL container
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      S3_BUCKET: $S3_BUCKET
    depends_on:
      - db

volumes:
  pgdata:
